---
sidebar: sidebar 
permalink: trident-use/worker-node-prep.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, nfs, iscsi, kubernetes clusters 
summary: Todos los nodos de trabajo del clúster de Kubernetes deben poder montar los volúmenes que haya aprovisionado para los pods. Si utiliza el controlador ontap-nas, ontap-nas-Economy, ontap-nas-flexgroup para uno de los back-ends, sus nodos de trabajo necesitan las herramientas NFS. De lo contrario, se necesitan las herramientas iSCSI. 
---
= Prepare el nodo de trabajo
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Todos los nodos de trabajo del clúster de Kubernetes deben poder montar los volúmenes que haya aprovisionado para los pods. Si está utilizando la `ontap-nas`, `ontap-nas-economy`, o. `ontap-nas-flexgroup` Controlador para uno de los back-ends, los nodos de trabajador necesitan las herramientas NFS. De lo contrario, se necesitan las herramientas iSCSI.

Las versiones recientes de RedHat CoreOS tienen instaladas de forma predeterminada NFS e iSCSI.


WARNING: Siempre debe reiniciar los nodos de trabajo después de instalar las herramientas NFS o iSCSI, o bien es posible que se produzca un error en la asociación de volúmenes a contenedores.



== Detección del servicio de nodos

A partir de 22.07, Astra Trident intenta detectar automáticamente si el nodo es capaz de ejecutar servicios iSCSI o NFS. Astra Trident crea eventos para que el nodo identifique los servicios detectados. Es posible revisar estos eventos con el comando:

[listing]
----
kubectl get event -A --field-selector involvedObject.name=<Kubernetes node name>
----
Trident también identifica los servicios habilitados para cada nodo en la CR del nodo de Trident. Para ver los servicios detectados, utilice el comando:

[listing]
----
tridentctl get node -o wide -n <Trident namespace>
----

NOTE: La detección de servicios de nodo identifica los servicios detectados, pero no garantiza que los servicios se configuren correctamente. Por el contrario, la ausencia de un servicio detectado no garantiza que se produzca un error en el montaje del volumen.



== Volúmenes de NFS

[cols="3*"]
|===
| Protocolo | De NetApp | Comandos 


| NFS  a| 
RHEL/CentOS 7
 a| 
`sudo yum install -y nfs-utils`



| NFS  a| 
Ubuntu
 a| 
`sudo apt-get install -y nfs-common`

|===

NOTE: Debe asegurarse de que el servicio NFS se haya iniciado durante el arranque.



== Volúmenes iSCSI

Tenga en cuenta lo siguiente al usar volúmenes iSCSI:

* Cada nodo del clúster de Kubernetes debe tener un IQN único. *Este es un requisito previo necesario*.
* Si utiliza RHCOS versión 4.5 o posterior, u otra distribución Linux compatible con RHEL, con `solidfire-san` Controlador y Element OS 12.5 o anterior, asegúrese de que el algoritmo de autenticación CHAP esté establecido en MD5 in `/etc/iscsi/iscsid.conf`. Los algoritmos CHAP SHA1, SHA-256 y SHA3-256 compatibles con FIPS están disponibles con Element 12.7.
+
[listing]
----
sudo sed -i 's/^\(node.session.auth.chap_algs\).*/\1 = MD5/' /etc/iscsi/iscsid.conf
----
* Cuando utilice nodos de trabajo que ejecutan RHEL/RedHat CoreOS con VP iSCSI, asegúrese de especificar el `discard` MountOption en StorageClass para realizar un reclamación de espacio en línea. Consulte https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["La documentación de redhat"^].


[cols="3*"]
|===
| Protocolo | De NetApp | Comandos 


| ISCSI  a| 
RHEL/CentOS
 a| 
. Instale los siguientes paquetes del sistema:
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`

. Compruebe que la versión de iscsi-initiator-utils sea 6.2.0.874-2.el7 o posterior:
+
`rpm -q iscsi-initiator-utils`

. Configure el escaneo en manual:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. Activar accesos múltiples:
+
`sudo mpathconf --enable --with_multipathd y --find_multipaths n`

+

NOTE: Asegúrese `etc/multipath.conf` contiene `find_multipaths no` inferior `defaults`.

. Asegúrese de que así sea `iscsid` y.. `multipathd` están en ejecución:
+
`sudo systemctl enable --now iscsid multipathd`

. Activar e iniciar `iscsi`:
+
`sudo systemctl enable --now iscsi`





| ISCSI  a| 
Ubuntu
 a| 
. Instale los siguientes paquetes del sistema:
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`

. Compruebe que la versión Open-iscsi sea 2.0.874-5ubuntu2.10 o posterior (para bionic) o 2.0.874-7.1ubuntu6.1 o posterior (para focal):
+
`dpkg -l open-iscsi`

. Configure el escaneo en manual:
+
`sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf`

. Activar accesos múltiples:
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart`

+

NOTE: Asegúrese `etc/multipath.conf` contiene `find_multipaths no` inferior `defaults`.

. Asegúrese de que así sea `open-iscsi` y.. `multipath-tools` están habilitadas y en ejecución:
+
`sudo systemctl status multipath-tools`
`sudo systemctl enable --now open-iscsi.service`
`sudo systemctl status open-iscsi`



|===

NOTE: Para Ubuntu 18.04, debe descubrir los puertos de destino con `iscsiadm` antes de comenzar `open-iscsi` Para que se inicie el daemon iSCSI. También puede modificar el `iscsi` servicio para empezar `iscsid` automáticamente.
