---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy.html 
keywords: deploy, astra trident, methods, operator, tridentctl, helm 
summary: 'Puede poner en marcha Astra Trident con el operador de Trident o con `tridentctl`.' 
---
= Información general sobre la implementación
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede poner en marcha Astra Trident con el operador de Trident o con `tridentctl`.


NOTE: A partir de la versión 22.04, las claves AES ya no se regenerarán cada vez que se instale Astra Trident. Con este lanzamiento, Astra Trident instalará un nuevo objeto secreto que persiste en todas las instalaciones. Esto significa que, `tridentctl` En la versión 22.04 puede desinstalar versiones anteriores de Trident, pero las versiones anteriores no pueden desinstalar instalaciones de 22.04.



== Información crucial sobre Astra Trident 22.10

*Debe leer la siguiente información crítica antes de actualizar a Astra Trident 22.10.*

[WARNING]
.<strong> información de las Ocampo sobre la Astra Trident 22.10 </strong>
====
* Kubernetes 1.25 ahora es compatible con Trident. Debe actualizar a Astra Trident 22.10 antes de actualizar a Kubernetes 1.25.
* Astra Trident ahora cumple estrictamente el uso de la configuración de varias rutas en entornos SAN, con un valor recomendado de `find_multipaths: no` en el archivo multipath.conf.
+
Uso de la configuración sin multivía o el uso de `find_multipaths: yes` o. `find_multipaths: smart` el valor del archivo multipath.conf provocará fallos de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versión 21.07.



====


== Elija el método de implementación

Para determinar qué método de implementación utilizar, tenga en cuenta lo siguiente:



=== Cuándo utilizar el operador Trident

La link:kubernetes-deploy-operator.html["Operador de Trident"^] Es una excelente forma de gestionar de forma dinámica los recursos de Astra Trident y automatizar la fase de configuración. Hay algunos requisitos previos que deben cumplirse. Consulte link:requirements.html["los requisitos"^].

El operador de Trident ofrece varias ventajas como se describe a continuación.



==== Funcionalidad de reparación automática

Puede supervisar una instalación de Astra Trident y tomar medidas de forma activa para solucionar problemas, como, por ejemplo, cuándo se elimina la implementación o si se modifica por accidente. Cuando el operador se configura como una implementación, un `trident-operator-<generated-id>` se crea el pod. Este pod asocia un `TridentOrchestrator` CR con una instalación de Astra Trident y siempre garantiza que sólo haya una activa `TridentOrchestrator`. En otras palabras, el operador se asegura de que sólo hay una instancia de Astra Trident en el cluster y controla su configuración, asegurándose de que la instalación es idempotente. Cuando se realizan cambios en la instalación (como eliminar el despliegue o el conjunto de nodos), el operador los identifica y los corrige individualmente.



==== Actualizaciones sencillas en instalaciones existentes

Puede actualizar fácilmente una implementación existente con el operador. Sólo tiene que editar el `TridentOrchestrator` CR para realizar actualizaciones de una instalación. Por ejemplo, piense en una situación en la que necesita habilitar Astra Trident para generar registros de depuración.

Para hacer esto, parche su `TridentOrchestrator` para ajustar `spec.debug` para `true`:

[listing]
----
kubectl patch torc <trident-orchestrator-name> -n trident --type=merge -p '{"spec":{"debug":true}}'
----
Después `TridentOrchestrator` se actualiza, el operador procesa las actualizaciones y parches de la instalación existente. Esto puede activar la creación de nuevos POD para modificar la instalación según corresponda.



==== Gestiona automáticamente las actualizaciones de Kubernetes

Cuando la versión de Kubernetes del clúster se actualiza a una versión compatible, el operador actualiza una instalación existente de Astra Trident automáticamente y la cambia para garantizar que cumple los requisitos de la versión de Kubernetes.


NOTE: Si se actualiza el clúster a una versión no compatible, el operador evita la instalación de Astra Trident. Si ya se ha instalado Astra Trident con el operador, se muestra una advertencia para indicar que Astra Trident está instalada en una versión de Kubernetes no compatible.



==== Gestione los clústeres de Kubernetes con BlueXP (anteriormente Cloud Manager)

Con link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html["Astra Trident con BlueXP"^], Puede realizar una actualización a la versión más reciente de Astra Trident, agregar y gestionar clases de almacenamiento, conectarlos a entornos de trabajo y realizar backups de volúmenes persistentes mediante Cloud Backup Service. BlueXP admite la puesta en marcha de Astra Trident con el operador de Trident, ya sea manualmente o mediante Helm.



=== Cuándo usar Helm

Si dispone de otras aplicaciones que gestiona con Helm, empezando por Astra Trident 21.01, puede gestionar su puesta en marcha también mediante Helm.



=== Cuándo utilizarlo `tridenctl`

Si ya tiene una puesta en marcha existente que debe actualizarse a o si desea personalizar de forma altamente su puesta en marcha, debe plantearse utilizar link:kubernetes-deploy-tridentctl.html["tridentctl"^]. Este es el método convencional de puesta en marcha de Astra Trident.



== Consideraciones que tener en cuenta al mover entre métodos de implementación

No es difícil imaginar un escenario en el que se desee moverse entre los métodos de implementación. Debe tener en cuenta lo siguiente antes de intentar moverse desde un `tridentctl` implementación en una implementación basada en operadores, o viceversa:

* Utilice siempre el mismo método para desinstalar Astra Trident. Si ha implementado con `tridentctl`, debe utilizar la versión adecuada de `tridentctl` Binario para desinstalar Astra Trident. Del mismo modo, si está desplegando con el operador, debe editar el `TridentOrchestrator` CR y SET `spec.uninstall=true` Para desinstalar Astra Trident.
* Si tiene una implementación basada en el operador que desea quitar y utilizar `tridentctl` Para poner en marcha Astra Trident, primero debe editar `TridentOrchestrator` y ajustar `spec.uninstall=true` Para desinstalar Astra Trident. A continuación, elimínelo `TridentOrchestrator` y la puesta en marcha del operador. A continuación, puede realizar la instalación mediante `tridentctl`.
* Si tiene una puesta en marcha manual basada en el operador y desea utilizar la puesta en marcha del operador de Trident basado en Helm, primero debe desinstalar manualmente al operador y, a continuación, realizar la instalación de Helm. De este modo, Helm puede poner en marcha el operador Trident con las etiquetas y anotaciones necesarias. Si no lo hace, la puesta en marcha del operador de Trident basado en Helm generará un error de validación de la etiqueta y un error de validación de la anotación. Si usted tiene un `tridentctl`La implementación basada en , puede utilizar la puesta en marcha basada en Helm sin que se produzcan problemas.




== Entender los modos de implementación

Existen tres formas de poner en marcha Astra Trident.



=== Implementación estándar

La puesta en marcha de Trident en un clúster de Kubernetes se traduce en que el instalador de Astra Trident realiza dos acciones:

* Obteniendo las imágenes del contenedor a través de Internet
* Crear una implementación y/o un conjunto de nodos demonset, que hace girar Astra Trident pods en todos los nodos elegibles del clúster de Kubernetes.


Una puesta en marcha estándar como esta se puede realizar de dos formas distintas:

* Uso `tridentctl install`
* Utilice el operador Trident. Es posible poner en marcha el operador de Trident de forma manual o mediante Helm.


Este modo de instalación es la forma más sencilla de instalar Astra Trident y funciona para la mayoría de los entornos que no imponen restricciones de red.



=== Puesta en marcha sin conexión

Para realizar una implementación con conexión inalámbrica, puede utilizar `--image-registry` marque al invocar `tridentctl install` para apuntar a un registro de imágenes privado. Si realiza la implementación con el operador de Trident, también es posible especificar otra opción `spec.imageRegistry` en la `TridentOrchestrator`. Este registro debe contener la https://hub.docker.com/r/netapp/trident/["Imagen de Trident"^], la https://hub.docker.com/r/netapp/trident-autosupport/["Imagen de Trident AutoSupport"^], Y las imágenes del sidecar CSI según lo requiera su versión Kubernetes.

Para personalizar su puesta en marcha, puede usar `tridentctl` Para generar los manifiestos para los recursos de Trident. Esto incluye la implementación, el conjunto demoníaco, la cuenta de servicio y el rol de clúster que crea Astra Trident como parte de su instalación.

Consulte estos enlaces para obtener más información sobre cómo personalizar la implementación:

* link:kubernetes-customize-deploy.html["Personalice la implementación basada en operador"^]
* 



IMPORTANT: Si está utilizando un repositorio de imágenes privado, debe agregar `/sig-storage` Al final de la dirección URL del registro privado. Cuando se utiliza un registro privado para `tridentctl` implementación, debe usar `--trident-image` y.. `--autosupport-image` en conjunto con `--image-registry`. Si va a poner en marcha Astra Trident con el operador Trident, asegúrese de que orchestrator CR incluya `tridentImage` y.. `autosupportImage` en los parámetros de instalación.



=== Puesta en marcha remota

Aquí encontrará una descripción de alto nivel del proceso de implementación remota:

* Despliegue la versión adecuada de `kubectl` En la máquina remota desde la que desea poner en marcha Astra Trident.
* Copie los archivos de configuración del clúster de Kubernetes y establezca el `KUBECONFIG` variable de entorno en el equipo remoto.
* Inicie un `kubectl get nodes` Comando para verificar que puede conectarse al clúster de Kubernetes necesario.
* Complete la implementación desde la máquina remota mediante los pasos de instalación estándar.




== Otras opciones de configuración conocidas

Al instalar Astra Trident en productos de la cartera tanzu de VMware:

* El clúster debe admitir cargas de trabajo con privilegios.
* La `--kubelet-dir` el indicador se debe establecer en la ubicación del directorio kubelet. De forma predeterminada, esta es `/var/vcap/data/kubelet`.
+
Especificación de la ubicación del kubelet mediante `--kubelet-dir` Sabe que funciona para el operador, Helm y. `tridentctl` implementaciones.


