---
sidebar: sidebar 
permalink: trident-concepts/ontap-drivers.html 
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers 
summary: Descubra cómo crear y usar un back-end de Element con la instalación de Trident. 
---
= Controladores ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident proporciona cinco controladores de almacenamiento exclusivos de ONTAP para comunicarse con clústeres de ONTAP. Obtenga más información sobre cómo se ocupa cada controlador de la creación de volúmenes y el control de acceso y sus capacidades.



== Obtenga información sobre los controladores de almacenamiento de ONTAP

[cols="5"]
|===
| Controlador | Protocolo | VolumeMode | Modos de acceso compatibles | Sistemas de archivos compatibles 


| `ontap-nas`  a| 
NFS
 a| 
Sistema de archivos
 a| 
RWO, ROX, RWX
 a| 
"", nfs



| `ontap-nas-economy`  a| 
NFS
 a| 
Sistema de archivos
 a| 
RWO, ROX, RWX
 a| 
"", nfs



| `ontap-nas-flexgroup`  a| 
NFS
 a| 
Sistema de archivos
 a| 
RWO, ROX, RWX
 a| 
"", nfs



| `ontap-san`  a| 
ISCSI
 a| 
Bloque
 a| 
RWO, ROX, RWX
 a| 
Sin sistema de archivos; dispositivo de bloque sin procesar



| `ontap-san`  a| 
ISCSI
 a| 
Sistema de archivos
 a| 
RWO, ROX

RWX no está disponible en el modo de volumen del sistema de archivos.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Bloque
 a| 
RWO, ROX, RWX
 a| 
Sin sistema de archivos; dispositivo de bloque sin procesar



| `ontap-san-economy`  a| 
ISCSI
 a| 
Sistema de archivos
 a| 
RWO, ROX

RWX no está disponible en el modo de volumen del sistema de archivos.
 a| 
`xfs`, `ext3`, `ext4`

|===

NOTE: Los back-ends de ONTAP se pueden autenticar con credenciales de inicio de sesión para un rol de seguridad (nombre de usuario/contraseña) o con la clave privada, y el certificado instalado en el clúster de ONTAP. Es posible actualizar los back-ends existentes para pasar de un modo de autenticación a otro con `tridentctl update backend`.
